### ISSUE TITLE
Upload failures

### ISSUE THREAD

**Issue by RivenSkaye** [Savolae/catbox#34]
I'm currently having trouble getting any uploads to go through, specifically the permanent kind.
Litterbox works just fine, and the web interface for both endpoints is perfectly functional too. It's specifically the `catbox upload` command that doesn't work.

Things I've tried, from both MSYS2/MingW64 and plain old CMD.exe envs:
- Uploading with userhash
- uploading without userhash
- Using litter instead (<-- this works)
- different file types
- different sizes (a few kB instead of a few MB)

Version: 0.8.1 (latest, built from git using `cargo install`)
I'll happily provide logs or anything of the sort if there's a way to force creation of those. Currently I just get `uploading mpv.log failed` (made for a good test file)

**Comment by DCNick3** [comment]
It seems that catbox doesn't like reqwests's user agent (or lack thereof?) and silently closes the connection (probably due to a php error or whatnot).

If I set the user-agent header to something meaningful, it stops being a problem

**Comment by HaizeSteiner** [comment]
How do i fix it?

**Comment by RivenSkaye** [comment]
> How do i fix it?

@HaizeSteiner I already fixed it, and the PR was merged already. But I forgot to fix the lockfile so you'll want to either install my forked repo, or clone this one and update the lockfile first.
The wasiest way would be to run `cargo install catbox --git https://github.com/RivenSkaye/catbox`
